name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    uses: latamgateway/ruby-linters-latam/.github/workflows/rspec.yml@main
  lint:
    uses: latamgateway/ruby-linters-latam/.github/workflows/lint.yml@main
  review:
    uses: latamgateway/ruby-linters-latam/.github/workflows/review.yml@review

  type-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["2.7.6"]
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Generate types for gems
        run: bundle exec tapioca init

      - name: Check Types
        run: bundle exec srb tc
