---
name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    uses: latamgateway/ruby-linters-latam/.github/workflows/rspec.yml@0.1.0
